#!/usr/bin/env bash

eval "$(cat "$(which carla)" | grep export)"

export YABRIDGE_DEBUG_FILE=$HOME/.cache/yabridge.log
export YABRIDGE_DEBUG_LEVEL=1

export LD_LIBRARY_PATH=/run/current-system/sw/lib 

bitwig-studio "$@"
