#!/usr/bin/env bash

export YABRIDGE_DEBUG_FILE=$HOME/.cache/yabridge.log
export YABRIDGE_DEBUG_LEVEL=1

if test -e $YABRIDGE_DEBUG_FILE; then
  rm $YABRIDGE_DEBUG_FILE
fi

export SHELL=/bin/sh

exec carla "${@:-}"
