#!/usr/bin/env bash

# Environment
# ===========

# gtk2 theme
# ----------
export GTK2_RC_FILES=/home/nyarla/.gtkrc-2.0

# lang
# ----
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF8

# GUI
# ===

# wallpaper
# ---------
hsetroot -full ~/local/wallpapers/nix-wallpaper-mosaic-blue.png &

# dock
# ----
lxqt-panel >/dev/null 2>&1 &

# Services
# ========

# on NyZen9
if test -e /dev/disk/by-uuid/05b4746c-9eed-4228-b306-922a9ef6ac4e ; then
  if test ! -d /run/media/nyarla/data; then
    gio mount -d 05b4746c-9eed-4228-b306-922a9ef6ac4e /run/media/nyarla/data &
  fi
fi

if test -e /dev/disk/by-uuid/2d5042e0-906c-4fda-8653-9cd105ea34ca ; then
  if test ! -d /run/media/nyarla/kvm; then
    gio mount -d 2d5042e0-906c-4fda-8653-9cd105ea34ca /run/media/nyarla/kvm &
  fi
fi
  
# ibus
# ----
ibus-daemon -drx

# calibre
# -------
calibre --start-in-tray &
