#!/usr/bin/env bash

# Environment
# ===========

# gtk2 theme
# ----------
export GTK2_RC_FILES=/home/nyarla/.gtkrc-2.0

# lang
# ----
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF8

# GUI
# ===

# wallpaper
# ---------
hsetroot -full ~/local/wallpapers/nix-wallpaper-mosaic-blue.png

# dock
# ----
pkill lxqt-panel || true
lxqt-panel >/dev/null 2>&1 &

# Services
# ========

# on NyZen9
if test -e /dev/disk/by-uuid/05b4746c-9eed-4228-b306-922a9ef6ac4e ; then
  if test ! -d /run/media/nyarla/data; then
    gio mount -d 05b4746c-9eed-4228-b306-922a9ef6ac4e /run/media/nyarla/data &
  fi
fi

# ibus
# ----
ibus-daemon -drx

# calibre
# -------
if type calibre >/dev/null 2>&1 ; then
  pkill calibre || true
  calibre --start-in-tray &
fi
