#!/usr/bin/env bash

put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }

color_00=00/00/00
color_01=FF/66/33
color_02=CC/FF/00
color_03=FF/CC/33
color_04=00/CC/FF
color_05=CC/99/CC
color_06=00/CC/CC
color_07=F9/F9/F9

put_template  0 $color_00
put_template  1 $color_01
put_template  2 $color_02
put_template  3 $color_03
put_template  4 $color_04
put_template  5 $color_05
put_template  6 $color_06
put_template  7 $color_07
put_template  8 $color_00
put_template  9 $color_01
put_template 10 $color_02
put_template 11 $color_03
put_template 12 $color_04
put_template 13 $color_05
put_template 14 $color_06
put_template 15 $color_07

