#!/usr/bin/env sh

export WINEPREFIX=/run/media/nyarla/src/local/daw/daw/FLStudio
export LD_PRELOAD=

cd $WINEPREFIX

# wineasio.dll
wine64 regsvr32 wineasio.dll

# qjackctl
qjackctl &

# FL Studio
exec wine explorer 'C:\Program Files\Image-Line\FL Studio 20\FL64.exe'
